<?php

namespace Database\Seeders;

use App\Models\Order;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orders = [
            // Órdenes del mes pasado (Septiembre 2024)
            [
                'user_id' => 2,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 45.50,
                'taxes' => 7.28,
                'total' => 52.78,
                'delivery_address' => 'Avenida 2 #456',
                'contact_phone' => '+1 555-0102',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 9, 5, 12, 30, 0),
                'delivered_date' => Carbon::create(2024, 9, 5, 13, 15, 0),
                'created_at' => Carbon::create(2024, 9, 5, 12, 30, 0),
                'updated_at' => Carbon::create(2024, 9, 5, 13, 15, 0),
            ],
            [
                'user_id' => 3,
                'status' => 'delivered',
                'service_type' => 'pickup',
                'subtotal' => 32.00,
                'taxes' => 5.12,
                'total' => 37.12,
                'delivery_address' => null,
                'contact_phone' => '+1 555-0103',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 9, 8, 14, 15, 0),
                'delivered_date' => Carbon::create(2024, 9, 8, 15, 0, 0),
                'created_at' => Carbon::create(2024, 9, 8, 14, 15, 0),
                'updated_at' => Carbon::create(2024, 9, 8, 15, 0, 0),
            ],
            [
                'user_id' => 4,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 67.80,
                'taxes' => 10.85,
                'total' => 78.65,
                'delivery_address' => 'Calle 4 #321',
                'contact_phone' => '+1 555-0104',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 9, 12, 18, 45, 0),
                'delivered_date' => Carbon::create(2024, 9, 12, 19, 45, 0),
                'created_at' => Carbon::create(2024, 9, 12, 18, 45, 0),
                'updated_at' => Carbon::create(2024, 9, 12, 19, 45, 0),
            ],
            [
                'user_id' => 5,
                'status' => 'delivered',
                'service_type' => 'pickup',
                'subtotal' => 28.50,
                'taxes' => 4.56,
                'total' => 33.06,
                'delivery_address' => null,
                'contact_phone' => '+1 555-0105',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 9, 15, 11, 20, 0),
                'delivered_date' => Carbon::create(2024, 9, 15, 11, 50, 0),
                'created_at' => Carbon::create(2024, 9, 15, 11, 20, 0),
                'updated_at' => Carbon::create(2024, 9, 15, 11, 50, 0),
            ],
            [
                'user_id' => 6,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 54.20,
                'taxes' => 8.67,
                'total' => 62.87,
                'delivery_address' => 'Boulevard 6 #987',
                'contact_phone' => '+1 555-0106',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 9, 18, 19, 30, 0),
                'delivered_date' => Carbon::create(2024, 9, 18, 20, 30, 0),
                'created_at' => Carbon::create(2024, 9, 18, 19, 30, 0),
                'updated_at' => Carbon::create(2024, 9, 18, 20, 30, 0),
            ],

            // Órdenes de este mes (Octubre 2024)
            [
                'user_id' => 2,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 41.00,
                'taxes' => 6.56,
                'total' => 47.56,
                'delivery_address' => 'Avenida 2 #456',
                'contact_phone' => '+1 555-0102',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 10, 2, 13, 0, 0),
                'delivered_date' => Carbon::create(2024, 10, 2, 14, 0, 0),
                'created_at' => Carbon::create(2024, 10, 2, 13, 0, 0),
                'updated_at' => Carbon::create(2024, 10, 2, 14, 0, 0),
            ],
            [
                'user_id' => 4,
                'status' => 'delivered',
                'service_type' => 'pickup',
                'subtotal' => 38.90,
                'taxes' => 6.22,
                'total' => 45.12,
                'delivery_address' => null,
                'contact_phone' => '+1 555-0104',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 10, 3, 17, 15, 0),
                'delivered_date' => Carbon::create(2024, 10, 3, 18, 0, 0),
                'created_at' => Carbon::create(2024, 10, 3, 17, 15, 0),
                'updated_at' => Carbon::create(2024, 10, 3, 18, 0, 0),
            ],
            [
                'user_id' => 5,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 72.50,
                'taxes' => 11.60,
                'total' => 84.10,
                'delivery_address' => 'Avenida 5 #654',
                'contact_phone' => '+1 555-0105',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 10, 4, 20, 0, 0),
                'delivered_date' => Carbon::create(2024, 10, 4, 21, 15, 0),
                'created_at' => Carbon::create(2024, 10, 4, 20, 0, 0),
                'updated_at' => Carbon::create(2024, 10, 4, 21, 15, 0),
            ],
            [
                'user_id' => 6,
                'status' => 'delivered',
                'service_type' => 'pickup',
                'subtotal' => 29.80,
                'taxes' => 4.77,
                'total' => 34.57,
                'delivery_address' => null,
                'contact_phone' => '+1 555-0106',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 10, 5, 12, 45, 0),
                'delivered_date' => Carbon::create(2024, 10, 5, 13, 15, 0),
                'created_at' => Carbon::create(2024, 10, 5, 12, 45, 0),
                'updated_at' => Carbon::create(2024, 10, 5, 13, 15, 0),
            ],
            [
                'user_id' => 7,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 55.60,
                'taxes' => 8.90,
                'total' => 64.50,
                'delivery_address' => 'Calle 7 #159',
                'contact_phone' => '+1 555-0107',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::create(2024, 10, 6, 15, 30, 0),
                'delivered_date' => Carbon::create(2024, 10, 6, 16, 45, 0),
                'created_at' => Carbon::create(2024, 10, 6, 15, 30, 0),
                'updated_at' => Carbon::create(2024, 10, 6, 16, 45, 0),
            ],

            // Órdenes de hoy (fecha dinámica)
            [
                'user_id' => 2,
                'status' => 'delivered',
                'service_type' => 'delivery',
                'subtotal' => 48.90,
                'taxes' => 7.82,
                'total' => 56.72,
                'delivery_address' => 'Avenida 2 #456',
                'contact_phone' => '+1 555-0102',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::today()->setTime(10, 0, 0),
                'delivered_date' => Carbon::today()->setTime(11, 15, 0),
                'created_at' => Carbon::today()->setTime(10, 0, 0),
                'updated_at' => Carbon::today()->setTime(11, 15, 0),
            ],
            [
                'user_id' => 8,
                'status' => 'ready',
                'service_type' => 'pickup',
                'subtotal' => 35.00,
                'taxes' => 5.60,
                'total' => 40.60,
                'delivery_address' => null,
                'contact_phone' => '+1 555-0108',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::today()->setTime(11, 30, 0),
                'ready_date' => Carbon::today()->setTime(12, 15, 0),
                'created_at' => Carbon::today()->setTime(11, 30, 0),
                'updated_at' => Carbon::today()->setTime(12, 15, 0),
            ],
            [
                'user_id' => 9,
                'status' => 'preparing',
                'service_type' => 'delivery',
                'subtotal' => 62.30,
                'taxes' => 9.97,
                'total' => 72.27,
                'delivery_address' => 'Boulevard 9 #951',
                'contact_phone' => '+1 555-0109',
                'payment_method' => 'efectivo_internacional',
                'currency' => 'internacional',
                'order_date' => Carbon::today()->setTime(12, 0, 0),
                'preparing_date' => Carbon::today()->setTime(12, 10, 0),
                'created_at' => Carbon::today()->setTime(12, 0, 0),
                'updated_at' => Carbon::today()->setTime(12, 10, 0),
            ],
            [
                'user_id' => 10,
                'status' => 'pending',
                'service_type' => 'pickup',
                'subtotal' => 27.50,
                'taxes' => 4.40,
                'total' => 31.90,
                'delivery_address' => null,
                'contact_phone' => '+1 555-0110',
                'payment_method' => 'tarjeta_credito',
                'currency' => 'internacional',
                'order_date' => Carbon::today()->setTime(13, 0, 0),
                'pending_date' => Carbon::today()->setTime(13, 0, 0),
                'created_at' => Carbon::today()->setTime(13, 0, 0),
                'updated_at' => Carbon::today()->setTime(13, 0, 0),
            ],
        ];

        foreach ($orders as $order) {
            Order::create($order);
        }
    }
}
