<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Limpiar la tabla antes de insertar
        DB::table('users')->delete();

        // Generar el hash una sola vez para reutilizarlo
        $hashedPassword = Hash::make('Grecia-123');

        DB::table('users')->insert([
            [
                'name' => 'Admin',
                'last_name' => 'Principal',
                'email' => 'admin@restaurante.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => null,
                'address' => null,
                'profile_picture' => null,
                'role' => 'admin',
                'status' => 'active',
                'registration_date' => '2025-11-04 15:17:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2025-11-04 15:17:00',
                'updated_at' => '2025-11-04 15:17:00',
            ],
            [
                'name' => 'Juan',
                'last_name' => 'Pérez',
                'email' => 'juan@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0101',
                'address' => 'Calle 1 #123',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-01-15 14:30:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-01-15 14:30:00',
                'updated_at' => '2024-01-15 14:30:00',
            ],
            [
                'name' => 'María',
                'last_name' => 'González',
                'email' => 'maria@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0102',
                'address' => 'Avenida 2 #456',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-02-20 18:15:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-02-20 18:15:00',
                'updated_at' => '2024-02-20 18:15:00',
            ],
            [
                'name' => 'Carlos',
                'last_name' => 'Rodríguez',
                'email' => 'carlos@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0103',
                'address' => 'Boulevard 3 #789',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'inactive',
                'registration_date' => '2024-03-10 13:45:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-03-10 13:45:00',
                'updated_at' => '2024-03-10 13:45:00',
            ],
            [
                'name' => 'Ana',
                'last_name' => 'Martínez',
                'email' => 'ana@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0104',
                'address' => 'Calle 4 #321',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-04-05 20:20:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-04-05 20:20:00',
                'updated_at' => '2024-04-05 20:20:00',
            ],
            [
                'name' => 'Luis',
                'last_name' => 'López',
                'email' => 'luis@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0105',
                'address' => 'Avenida 5 #654',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-05-12 15:00:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-05-12 15:00:00',
                'updated_at' => '2024-05-12 15:00:00',
            ],
            [
                'name' => 'Sofia',
                'last_name' => 'Hernández',
                'email' => 'sofia@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0106',
                'address' => 'Boulevard 6 #987',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-06-18 17:30:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-06-18 17:30:00',
                'updated_at' => '2024-06-18 17:30:00',
            ],
            [
                'name' => 'Diego',
                'last_name' => 'García',
                'email' => 'diego@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0107',
                'address' => 'Calle 7 #159',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-07-22 19:45:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-07-22 19:45:00',
                'updated_at' => '2024-07-22 19:45:00',
            ],
            [
                'name' => 'Elena',
                'last_name' => 'Díaz',
                'email' => 'elena@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0108',
                'address' => 'Avenida 8 #753',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-08-30 14:15:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-08-30 14:15:00',
                'updated_at' => '2024-08-30 14:15:00',
            ],
            [
                'name' => 'Miguel',
                'last_name' => 'Ramírez',
                'email' => 'miguel@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0109',
                'address' => 'Boulevard 9 #951',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-09-14 16:00:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-09-14 16:00:00',
                'updated_at' => '2024-09-14 16:00:00',
            ],
            [
                'name' => 'Laura',
                'last_name' => 'Torres',
                'email' => 'laura@example.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+1 555-0110',
                'address' => 'Calle 10 #852',
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2024-10-01 18:30:00',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2024-10-01 18:30:00',
                'updated_at' => '2024-10-01 18:30:00',
            ],
            [
                'name' => 'Ikabaru Alejandro',
                'last_name' => 'Garcia Torres',
                'email' => 'ikabarugarcia12@gmail.com',
                'email_verified_at' => null,
                'password' => $hashedPassword,
                'phone_number' => '+58 414 2591853',
                'address' => null,
                'profile_picture' => null,
                'role' => 'client',
                'status' => 'active',
                'registration_date' => '2025-11-11 15:30:17',
                'last_connection' => null,
                'remember_token' => null,
                'created_at' => '2025-11-11 19:30:17',
                'updated_at' => '2025-11-11 19:30:17',
            ],
        ]);
    }
}

