import {
    BankOutlined,
    BranchesOutlined,
    CreditCardOutlined,
    DashboardOutlined,
    DollarOutlined,
    FileDoneOutlined,
    FileOutlined,
    GoldOutlined,
    IdcardOutlined,
    InboxOutlined,
    LinkOutlined,
    ProductOutlined,
    ShopOutlined,
    StarOutlined,
    TeamOutlined,
    UserOutlined,
} from "@ant-design/icons";
import type { ResourceProps } from "@refinedev/core";

export const refineResources: ResourceProps[] = [
    {
        name: "dashboard",
        list: "/dashboard",
        meta: {
            canDelete: true,
            icon: <DashboardOutlined />,
        },
    },
    {
        name: "personas",
        meta: {
            label: "Personas",
            icon: <TeamOutlined />,
        },
    },
    {
        name: "tiendas",
        meta: {
            label: "Tiendas",
            icon: <ShopOutlined />,
        },
    },
    {
        name: "productos",
        meta: {
            label: "Productos",
            icon: <GoldOutlined />,
        },
    },
    {
        name: "pagos",
        meta: {
            label: "Pagos",
            icon: <DollarOutlined />,
        },
    },
    {
        name: "users",
        list: "/users",
        create: "/users/create",
        edit: "/users/edit/:id",
        show: "/users/show/:id",
        meta: {
            label: "Usuarios",
            parent: "personas",
            canDelete: true,
            icon: <UserOutlined />,
        },
    },
    {
        name: "clients",
        list: "/clients",
        create: "/clients/create",
        edit: "/clients/edit/:id",
        show: "/clients/show/:id",
        meta: {
            label: "Clientes",
            parent: "personas",
            canDelete: true,
            icon: <IdcardOutlined />,
        },
    },
    {
        name: "employees",
        list: "/employees",
        create: "/employees/create",
        edit: "/employees/edit/:id",
        show: "/employees/show/:id",
        meta: {
            label: "Empleados",
            parent: "personas",
            canDelete: true,
            icon: <TeamOutlined />,
        },
    },
    {
        name: "branches",
        list: "/branches",
        create: "/branches/create",
        edit: "/branches/edit/:id",
        show: "/branches/show/:id",
        meta: {
            label: "Sucursales",
            parent: "tiendas",
            canDelete: true,
            icon: <BranchesOutlined />,
        },
    },
    {
        name: "evaluations",
        list: "/evaluations",
        create: "/evaluations/create",
        edit: "/evaluations/edit/:id",
        show: "/evaluations/show/:id",
        meta: {
            label: "Evaluaciones",
            parent: "tiendas",
            canDelete: true,
            icon: <StarOutlined />,
        },
    },
    {
        name: "products",
        list: "/products",
        create: "/products/create",
        edit: "/products/edit/:id",
        show: "/products/show/:id",
        meta: {
            label: "Productos",
            parent: "productos",
            canDelete: true,
            icon: <InboxOutlined />,
        },
    },
    {
        name: "categories",
        list: "/categories",
        create: "/categories/create",
        edit: "/categories/edit/:id",
        show: "/categories/show/:id",
        meta: {
            label: "Categorías",
            parent: "productos",
            canDelete: true,
            icon: <ProductOutlined />,
        },
    },
    {
        name: "product-branches",
        list: "/product-branches",
        create: "/product-branches/create",
        edit: "/product-branches/edit/:id",
        show: "/product-branches/show/:id",
        meta: {
            label: "Productos por Sucursal",
            parent: "productos",
            canDelete: true,
            icon: <LinkOutlined />,
        },
    },
    {
        name: "orders",
        list: "/orders",
        create: "/orders/create",
        edit: "/orders/edit/:id",
        show: "/orders/show/:id",
        meta: {
            label: "Ordenes",
            parent: "pagos",
            canDelete: true,
            icon: <FileOutlined />,
        },
    },
    {
        name: "order-details",
        list: "/order-details",
        create: "/order-details/create",
        edit: "/order-details/edit/:id",
        show: "/order-details/show/:id",
        meta: {
            label: "Detalles de Ordenes",
            parent: "pagos",
            canDelete: true,
            icon: <FileDoneOutlined />,
        },
    },
    {
        name: "order-payments",
        list: "/order-payments",
        create: "/order-payments/create",
        edit: "/order-payments/edit/:id",
        show: "/order-payments/show/:id",
        meta: {
            label: "Pagos de Ordenes",
            parent: "pagos",
            canDelete: true,
            icon: <DollarOutlined />,
        },
    },
    {
        name: "payment-methods",
        list: "/payment-methods",
        show: "/payment-methods/show/:id",
        meta: {
            label: "Metodos de Pago",
            parent: "pagos",
            canDelete: false,
            icon: <CreditCardOutlined />,
        },
    },
    {
        name: "banks",
        list: "/banks",
        show: "/banks/show/:id",
        meta: {
            label: "Bancos",
            parent: "pagos",
            canDelete: false,
            icon: <BankOutlined />,
        },
    },
];
